// controlled airspace
var arinc_spec_as_ctl = {
	1: {
		length: 132,
		fields: [{
			key: 'record_type',
			type: 'string',
			length: 1,
			startingPosition: 1,
			defaultValue: 'S'
		}, {
			key: 'area',
			type: 'string',
			length: 3,
			startingPosition: 2,
			defaultValue: 'EUR'
		}, {
			key: 'section',
			type: 'string',
			length: 1,
			startingPosition: 5,
			defaultValue: 'U'
		}, {
			key: 'sub_section',
			type: 'string',
			length: 1,
			startingPosition: 6,
			defaultValue: 'C'
		}, {
			key: 'icao_code',
			type: 'string',
			length: 2,
			startingPosition: 7
		}, {
			key: 'as_type',
			type: 'string',
			length: 1,
			startingPosition: 9
		}, {
			key: 'as_center',
			type: 'string',
			length: 5,
			startingPosition: 10
		}, { // PA=airport,EA=waypoint,DB=NDB navaid depending on center
			key: 'sec_code2',
			type: 'string',
			length: 1,
			startingPosition: 15,
			defaultValue: 'P',
		}, {
			key: 'sub_code2',
			type: 'string',
			length: 1,
			startingPosition: 16,
			defaultValue: 'A',
		}, {
			key: 'as_class',
			type: 'string',
			length: 1,
			startingPosition: 17
		}, {
			key: 'multi_cd',
			type: 'string',
			length: 1,
			startingPosition: 20
		}, {
			key: 'seq_nr',
			type: 'integer',
			length: 4,
			startingPosition: 21
		}, {
			key: 'cont_nr',
			type: 'integer',
			length: 1,
			startingPosition: 25
		}, { //TODO B=all altitudes
			key: 'level',
			type: 'string',
			length: 1,
			startingPosition: 26,
			defaultValue: 'B'
		}, { //TODO G=great circle
			key: 'boundary_via',
			type: 'string',
			length: 2,
			startingPosition: 31,
			defaultValue: 'G '
		}, {
			key: 'latitude',
			type: 'string',
			length: 9,
			startingPosition: 33
		}, {
			key: 'longitude',
			type: 'string',
			length: 10,
			startingPosition: 42
		}, {
			key: 'lower',
			type: 'integer',
			length: 5,
			startingPosition: 82
		}, {
			key: 'lower_unit',
			type: 'string',
			length: 1,
			startingPosition: 87
		}, { // M = MSL, A = AGL
			key: 'upper',
			type: 'integer',
			length: 5,
			startingPosition: 88
		}, { // M = MSL, A = AGL
			key: 'upper_unit',
			type: 'string',
			length: 1,
			startingPosition: 93
		}, {
			key: 'name',
			type: 'string',
			length: 30,
			startingPosition: 94
		}, {
			key: 'record_nr',
			type: 'integer',
			length: 5,
			startingPosition: 124
		}, {
			key: 'cycle',
			type: 'integer',
			length: 4,
			startingPosition: 129
		}, ]
	},
	2: {
		length: 132,
		fields: [{
			key: 'record_type',
			type: 'string',
			length: 1,
			startingPosition: 1,
			defaultValue: 'S'
		}, {
			key: 'area',
			type: 'string',
			length: 3,
			startingPosition: 2,
			defaultValue: 'EUR'
		}, {
			key: 'section',
			type: 'string',
			length: 1,
			startingPosition: 5,
			defaultValue: 'U'
		}, {
			key: 'sub_section',
			type: 'string',
			length: 1,
			startingPosition: 6,
			defaultValue: 'C'
		}, {
			key: 'icao_code',
			type: 'string',
			length: 2,
			startingPosition: 7
		}, {
			key: 'as_type',
			type: 'string',
			length: 1,
			startingPosition: 9
		}, {
			key: 'as_center',
			type: 'string',
			length: 5,
			startingPosition: 10
		}, {
			key: 'sec_code2',
			type: 'string',
			length: 1,
			startingPosition: 15,
			defaultValue: 'P',
		}, {
			key: 'sub_code2',
			type: 'string',
			length: 1,
			startingPosition: 16,
			defaultValue: 'A',
		}, {
			key: 'as_class',
			type: 'string',
			length: 1,
			startingPosition: 17
		}, {
			key: 'multi_cd',
			type: 'string',
			length: 1,
			startingPosition: 20
		}, {
			key: 'seq_nr',
			type: 'integer',
			length: 4,
			startingPosition: 21
		}, {
			key: 'cont_nr',
			type: 'integer',
			length: 1,
			startingPosition: 25
		}, {
			key: 'appl_type',
			type: 'string',
			length: 1,
			startingPosition: 26
		}, {
			key: 'ctrl_agency',
			type: 'string',
			length: 24,
			startingPosition: 100
		}, {
			key: 'record_nr',
			type: 'integer',
			length: 5,
			startingPosition: 124
		}, {
			key: 'cycle',
			type: 'integer',
			length: 4,
			startingPosition: 129
		}, ]
	}
};

module.exports = arinc_spec_as_ctl;