// FIR/UIR
var arinc_spec_fir_uir = {
	1: {
		length: 132,
		defaultRequired: false,
		fields: [{
			key: 'record_type',
			type: 'string',
			length: 1,
			startingPosition: 1,
			defaultValue: 'U',
		}, {
			key: 'area',
			type: 'string',
			length: 3,
			startingPosition: 2,
			defaultValue: 'EUR'
		}, {
			key: 'section',
			type: 'string',
			length: 1,
			startingPosition: 5,
			defaultValue: 'U'
		}, {
			key: 'sub_section',
			type: 'string',
			length: 1,
			startingPosition: 6,
			defaultValue: 'F',
		}, {
			key: 'ident',
			type: 'string',
			length: 4,
			startingPosition: 7,
		}, {
			key: 'fir_address',
			type: 'string',
			length: 4,
			startingPosition: 11,
		}, {
			key: 'indicator',
			type: 'string',
			length: 1,
			startingPosition: 15,
		}, {
			key: 'seq_nr',
			type: 'string',
			length: 4,
			startingPosition: 16,
		}, {
			key: 'cont_nr',
			type: 'integer',
			length: 1,
			startingPosition: 20,
		}, {
			key: 'adj_fir',
			type: 'string',
			length: 4,
			startingPosition: 21,
		}, {
			key: 'adj_uir',
			type: 'string',
			length: 4,
			startingPosition: 25
		}, {
			key: 'rus',
			type: 'string',
			length: 1,
			startingPosition: 29,
		}, {
			key: 'rua',
			type: 'string',
			length: 1,
			startingPosition: 30,
		}, {
			key: 'entry',
			type: 'string',
			length: 1,
			startingPosition: 31,
		}, { //TODO G=great circle
			key: 'boundary_via',
			type: 'string',
			length: 2,
			startingPosition: 33,
			defaultValue: 'G '
		}, {
			key: 'latitude',
			type: 'string',
			length: 9,
			startingPosition: 35,
		}, {
			key: 'longitude',
			type: 'string',
			length: 10,
			startingPosition: 44,
		}, {
			key: 'arc_latitude',
			type: 'string',
			length: 9,
			startingPosition: 54,
		}, {
			key: 'arc_longitude',
			type: 'string',
			length: 10,
			startingPosition: 63,
		}, {
			key: 'arc_dist',
			type: 'string',
			length: 4,
			startingPosition: 73,
		}, {
			key: 'arc_brg',
			type: 'string',
			length: 4,
			startingPosition: 77,
		}, {
			key: 'fir_upper',
			type: 'string',
			length: 5,
			startingPosition: 81
		}, {
			key: 'uir_lower',
			type: 'string',
			length: 5,
			startingPosition: 86
		}, {
			key: 'uir_upper',
			type: 'string',
			length: 5,
			startingPosition: 91
		}, {
			key: 'tc_ind',
			type: 'string',
			length: 2,
			startingPosition: 96
		}, {
			key: 'name',
			type: 'string',
			length: 25,
			startingPosition: 99
		}, {
			key: 'record_nr',
			type: 'integer',
			length: 5,
			startingPosition: 124
		}, {
			key: 'cycle',
			type: 'integer',
			length: 4,
			startingPosition: 129
		}, ]
	},
	2: {
		length: 132,
		defaultRequired: false,
		fields: [{
			key: 'record_type',
			type: 'string',
			length: 1,
			startingPosition: 1,
			defaultValue: 'S'
		}, {
			key: 'area',
			type: 'string',
			length: 3,
			startingPosition: 2,
			defaultValue: 'EUR'
		}, {
			key: 'section',
			type: 'string',
			length: 1,
			startingPosition: 5,
			defaultValue: 'U'
		}, {
			key: 'sub_section',
			type: 'string',
			length: 1,
			startingPosition: 6,
			defaultValue: 'C'
		}, {
			key: 'ident',
			type: 'string',
			length: 4,
			startingPosition: 7,
		}, {
			key: 'fir_address',
			type: 'string',
			length: 4,
			startingPosition: 11,
		}, {
			key: 'indicator',
			type: 'string',
			length: 1,
			startingPosition: 15,
		}, {
			key: 'seq_nr',
			type: 'string',
			length: 4,
			startingPosition: 16,
		}, {
			key: 'cont_nr',
			type: 'integer',
			length: 1,
			startingPosition: 20,
		}, {
			key: 'appl_type',
			type: 'string',
			length: 1,
			startingPosition: 21,
		}, {
			key: 'name',
			type: 'string',
			length: 25,
			startingPosition: 99
		}, {
			key: 'record_nr',
			type: 'integer',
			length: 5,
			startingPosition: 124
		}, {
			key: 'cycle',
			type: 'integer',
			length: 4,
			startingPosition: 129
		}, ]
	},
};

module.exports = arinc_spec_fir_uir;