var arinc_spec_rwy = {
	1: {
		length: 132,
		fields: [{
			key: 'record_type',
			type: 'string',
			length: 1,
			startingPosition: 1,
			defaultValue: 'S'
		}, {
			key: 'area',
			type: 'string',
			length: 3,
			startingPosition: 2,
			defaultValue: 'EUR'
		}, {
			key: 'section',
			type: 'string',
			length: 1,
			startingPosition: 5
		}, {
			key: 'aprt_ident',
			type: 'string',
			length: 4,
			startingPosition: 7
		}, {
			key: 'icao_code',
			type: 'string',
			length: 2,
			startingPosition: 11
		}, {
			key: 'sub_section',
			type: 'string',
			length: 1,
			startingPosition: 13
		}, {
			key: 'ident',
			type: 'string',
			length: 5,
			startingPosition: 14
		}, {
			key: 'cont_nr',
			type: 'integer',
			length: 1,
			startingPosition: 22
		}, {
			key: 'rwy_len',
			type: 'integer',
			length: 5,
			startingPosition: 23
		}, {
			key: 'rwy_brg',
			type: 'integer',
			length: 4,
			startingPosition: 28
		}, {
			key: 'latitude',
			type: 'string',
			length: 9,
			startingPosition: 33
		}, {
			key: 'longitude',
			type: 'string',
			length: 10,
			startingPosition: 42
		}, {
			key: 'elevation',
			type: 'integer',
			length: 5,
			startingPosition: 67
		}, {
			key: 'dsplcd_thr',
			type: 'integer',
			length: 4,
			startingPosition: 72
		}, { // threshold crossing height, default 50ft TODO
			key: 'tch',
			type: 'integer',
			length: 2,
			startingPosition: 76,
			defaultValue: 50
		}, {
			key: 'rwy_width',
			type: 'integer',
			length: 3,
			startingPosition: 78
		}, {
			key: 'stopway',
			type: 'integer',
			length: 4,
			startingPosition: 87
		}, {
			key: 'name',
			type: 'string',
			length: 30,
			startingPosition: 94
		}, {
			key: 'record_nr',
			type: 'integer',
			length: 5,
			startingPosition: 124
		}, {
			key: 'cycle',
			type: 'integer',
			length: 4,
			startingPosition: 129
		}, ]
	}
};

module.exports = arinc_spec_rwy;