var arinc_spec_vordme = {
	1: {
		length: 132,
		fields: [{
			key: 'record_type',
			type: 'string',
			length: 1,
			startingPosition: 1,
			defaultValue: 'S'
		}, {
			key: 'area',
			type: 'string',
			length: 3,
			startingPosition: 2,
			defaultValue: 'EUR'
		}, {
			key: 'section',
			type: 'string',
			length: 1,
			startingPosition: 5
		}, {
			key: 'sub_section',
			type: 'string',
			length: 1,
			startingPosition: 6
		}, {
			key: 'arpt_ident',
			type: 'string',
			length: 4,
			startingPosition: 7
		}, {
			key: 'icao_code',
			type: 'string',
			length: 2,
			startingPosition: 11
		}, {
			key: 'vor_ident',
			type: 'string',
			length: 4,
			startingPosition: 14
		}, {
			key: 'vor_icao_code',
			type: 'string',
			length: 2,
			startingPosition: 20
		}, {
			key: 'cont_nr',
			type: 'integer',
			length: 1,
			startingPosition: 22
		}, {
			key: 'vor_freq',
			type: 'integer',
			length: 5,
			startingPosition: 23
		}, {
			key: 'navaid_class_type1',
			type: 'string',
			length: 1,
			startingPosition: 28
		}, {
			key: 'navaid_class_type2',
			type: 'string',
			length: 1,
			startingPosition: 29
		}, {
			key: 'navaid_class_range',
			type: 'string',
			length: 1,
			startingPosition: 30
		}, {
			key: 'navaid_class_addinfo',
			type: 'string',
			length: 1,
			startingPosition: 31
		}, {
			key: 'navaid_class_colocation',
			type: 'string',
			length: 1,
			startingPosition: 32
		}, {
			key: 'vor_latitude',
			type: 'string',
			length: 9,
			startingPosition: 33
		}, {
			key: 'vor_longitude',
			type: 'string',
			length: 10,
			startingPosition: 42
		}, {
			key: 'dme_ident',
			type: 'string',
			length: 4,
			startingPosition: 52
		}, {
			key: 'dme_latitude',
			type: 'string',
			length: 9,
			startingPosition: 56
		}, {
			key: 'dme_longitude',
			type: 'string',
			length: 10,
			startingPosition: 65
		}, {
			key: 'station_declination',
			type: 'string',
			length: 5,
			startingPosition: 75
		}, {
			key: 'dme_elevation',
			type: 'integer',
			length: 5,
			startingPosition: 80
		}, {
			key: 'merit',
			type: 'integer',
			length: 1,
			startingPosition: 85
		}, {
			key: 'freq_protection',
			type: 'integer',
			length: 3,
			startingPosition: 88,
			defaultValue: 40
		}, {
			key: 'datum_code',
			type: 'string',
			length: 3,
			startingPosition: 91,
			defaultValue: 'WGE'
		}, {
			key: 'navaid_name',
			type: 'string',
			length: 30,
			startingPosition: 94
		}, {
			key: 'record_nr',
			type: 'integer',
			length: 5,
			startingPosition: 124
		}, {
			key: 'cycle',
			type: 'integer',
			length: 4,
			startingPosition: 129
		}, ]
	}
};

module.exports = arinc_spec_vordme;