var arinc_spec_wp = {
	1: {
		length: 132,
		defaultRequired: false,
		fields: [{
			key: 'record_type',
			type: 'string',
			length: 1,
			startingPosition: 1,
			defaultValue: 'S'
		}, {
			key: 'area',
			type: 'string',
			length: 3,
			startingPosition: 2,
			defaultValue: 'EUR'
		}, {
			key: 'section',
			type: 'string',
			length: 1,
			startingPosition: 5
		}, {
			key: 'sub_section_6',
			type: 'string',
			length: 1,
			startingPosition: 6
		}, {
			key: 'aprt_ident',
			type: 'string',
			length: 4,
			startingPosition: 7
		}, {
			key: 'aprt_icao_code',
			type: 'string',
			length: 2,
			startingPosition: 11
		}, {
			key: 'sub_section_13',
			type: 'string',
			length: 1,
			startingPosition: 13
		}, {
			key: 'ident',
			type: 'string',
			length: 5,
			startingPosition: 14
		}, {
			key: 'icao_code',
			type: 'string',
			length: 2,
			startingPosition: 20
		}, {
			key: 'cont_nr',
			type: 'integer',
			length: 1,
			startingPosition: 22
		}, {
			key: 'wpt_type',
			type: 'string',
			length: 1,
			startingPosition: 27,
			defaultValue: 'V'
		}, {
			key: 'latitude',
			type: 'string',
			length: 9,
			startingPosition: 33
		}, {
			key: 'longitude',
			type: 'string',
			length: 10,
			startingPosition: 42
		}, {
			key: 'elevation',
			type: 'string',
			length: 5,
			startingPosition: 80
		}, {
			key: 'datum_code',
			type: 'string',
			length: 3,
			startingPosition: 85,
			defaultValue: 'WGE'
		}, {
			key: 'name_ind',
			type: 'string',
			length: 3,
			startingPosition: 96
		}, {
			key: 'name',
			type: 'string',
			length: 25,
			startingPosition: 99
		}, {
			key: 'record_nr',
			type: 'integer',
			length: 5,
			startingPosition: 124
		}, {
			key: 'cycle',
			type: 'integer',
			length: 4,
			startingPosition: 129
		}, ]
	}
};

module.exports = arinc_spec_wp;